### ISSUE TITLE
PPoPP Accepted and Submitted Papers

### ISSUE THREAD

**Issue by abhijangda** [emeryberger/csconferences#2]
Hello,

Accepted and submitted papers in PPoPP does not seem correct in the csv file.
I have compiled accepted and submitted papers data from PPoPP 2018 and after based on the front matter.

| PPoPP | Accepted | Total | Link-to-Front-Matter |
|------- | ----------- |  ----  |  ---------------------- |
| 2018 |  28  |  139  | https://dl.acm.org/doi/proceedings/10.1145/3178487 |
|2019  | 29   |   152 |   https://dl.acm.org/doi/proceedings/10.1145/3293883 |
|2020  | 28  |    121 |   https://dl.acm.org/doi/proceedings/10.1145/3332466 |
|2021 |  26 |     150 |   https://dl.acm.org/doi/proceedings/10.1145/3437801 |
|2022 |  29  |    118 |   https://dl.acm.org/doi/proceedings/10.1145/3503221 |
|2023 |  31 |     131 |   https://dl.acm.org/doi/proceedings/10.1145/3572848 |

Thank You

**Comment by emeryberger** [comment]
Interesting! I was relying on hotcrp.com for these stats, but they vary pretty widely from what's reported in the front matter (see below). Thanks for the update!

<img width="1186" alt="Screenshot 2023-03-11 at 3 27 26 PM" src="https://user-images.githubusercontent.com/1612723/224510203-a842de21-4704-47b6-9a76-337c0e333ec4.png">
