### ISSUE TITLE
Please Include Real-Time Systems Conferences

### ISSUE THREAD

**Issue by mnwrhsn** [emeryberger/csconferences#3]
Real-time systems (RTS) are a predominant domain in systems that have been around for over 4 decades. CSRankings also allows filtering institutions based on RTS publication statistics. I am requesting to include top real-time conferences (RTSS, RTAS, ECRTS) in this list.

Thank you!

**Comment by emeryberger** [comment]
Would you be willing to help? I’d welcome pull requests adding these. See `csconferences.csv` for the format. Please submit one pull request at a time for each conference. Thanks!

**Comment by mnwrhsn** [comment]
Sure, happy to help! Will do.

**Comment by emeryberger** [comment]
Please use the area abbreviation ‘bed’ (for embedded systems; this is the CSrankings abbreviation for this area); if you update `build.py`, use the title “Embedded & real-time systems”. Thanks!
