### ISSUE TITLE
ECCV Conference Counts

### ISSUE THREAD

**Issue by todddevice** [emeryberger/csconferences#7]
Faculty in my unit report:

> from the last few years, it seems that some papers from ECCV conference
> proceedings (likely those in the later volumes within the same years) are not counted in the 
> [csrankings.org](http://csrankings.org/), though ECCV is widely recognized as one of the top Computer Vision conference 
> as listed under [csrankings.org](http://csrankings.org/) and by the Computer Vision Research Community (via CVF).
> 
> This bug may have to do with the code indexing the conference volumes not beyond a certain 
> number (upper-bound too small?), as the number of papers in the conference increases.

I am told that ECCV creates multiple volumes within the same year for the same conference proceedings, and is a possible cause of this reported issue.

**Comment by emeryberger** [comment]
This has been fixed.
